import Image from "next/image";
import Logo from "./logo.png";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { WpSdk } from "@/utils/wp-sdk";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const siteData = await WpSdk.getSiteData();
  console.log(siteData);

  return (
    <html lang="en">
      <body
        className={inter.className + " container mx-auto"}
        style={{ backgroundColor: "rgb(235 235 235)" }}
      >
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <div className="nav mt-4">
          <Link href="/">
            <Image
              src={siteData.icon.img}
              alt="logo"
              width={75}
              height={75}
              className="inline-block mb-5"
            />
            <h1 className="text-xl font-bold inline-block">{siteData.name}</h1>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
